experiment:
  name: "maskrcnn_resnet50_fpn_transfer_real"
  seed: 42

model:
  type: "maskrcnn_resnet50_fpn"
  num_classes: 2
  pretrained_backbone: true

dataset:
  train: "../../../datasets/RealBubbles.coco-segmentation/train"
  val:   "../../../datasets/RealBubbles.coco-segmentation/val"
  test:  "../../../datasets/RealBubbles.coco-segmentation/test"

train:
  batch_size: 2
  epochs: 30
  lr: 0.0005
  backbone_lr_factor: 0.1
  lr_step_size: 7
  gamma: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  num_workers: 4
  print_freq: 20
  patience: 7

augmentation:
  strong_color_jitter: false
  blur: false
  rotation: false
  intensity_shift: false

logging:
  use_tensorboard: true
  log_dir: "runs/"

output:
  dir: "outputs/"

eval:
  score_thresh: 0.5
  min_area: 50
  mask_thresh: 0.5

transfer:
  init_checkpoint: "outputs/maskrcnn_r50_fpn_synth_20251120_1035/model_best.pth"
  strict_load: true
  freeze_backbone_epochs: 3
